version: "3.9"

services:
  pg-database:
    image: postgres:15.1-alpine3.17
    container_name: testflow-db
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres

  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    container_name: testflow-app
    volumes:
      - ./src:/code
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - pg-database

volumes:
  db-data:
